### ISSUE TITLE
Unable to pin new items: "r is not a function"

### ISSUE THREAD

**Issue by Leibniz137** [dappnode/DAppNodePackage-ipfs-pinner#27]
After filling in the form and pressing "Add", I see that the UI reports "Successfully added dweb", however the item does not get added to the table of pinned entries.

![ipfs-pinner-fail](https://user-images.githubusercontent.com/2193797/81310697-49910d80-9039-11ea-8d69-5ad61ce2f972.gif)

logs with debug level set:
```
Search
Filter by...
info Starting cache DB cacheDbPath: "/usr/src/app/data/cachedb.json"
info IPFS HTTP API ipfsApiUrl: "http://ipfs.dappnode:5001"
info IPFS Cluster HTTP API clusterApiUrl: "http://ipfs-cluster.dappnode:9094"
info Web3 connected (ethers 4.0.39): http://fullnode.dappnode:8545 
(node:1) V8: /usr/src/app/index.js:787 Invalid asm.js: Unexpected token
info Webserver on 80, /usr/src/app/dist 
debug Finished polling all sources stateChange: {
  "cacheChange": {},
  "sourcesToAdd": [],
  "sourcesToRemove": [],
  "assetsToAdd": [],
  "assetsToRemove": []
}
debug Applying state change stateChange: {
  "cacheChange": {},
  "sourcesToAdd": [],
  "sourcesToRemove": [],
  "assetsToAdd": [],
  "assetsToRemove": []
}
info Client connected AUpViYxpqaN0WMfEAAAA 
debug Applying state change stateChange: {
  "cacheChange": {},
  "sourcesToAdd": [
    {
      "multiname": "dweb/tornadocash.eth",
      "from": "user/12D3KooWEjz5ySHCp6erG4txh3whoKzwMmXhBAePxDGzb5vcbCfN"
    }
  ],
  "sourcesToRemove": [],
  "assetsToAdd": [],
  "assetsToRemove": []
}
error TypeError: r is not a function
    at b.fetch (/usr/src/app/webpack:/node_modules/ipfs-utils/src/http.js:141:36)
    at b.call [as fetch] (/usr/src/app/webpack:/node_modules/ipfs-http-client/src/lib/core.js:148:20)
    at b.fetch [as post] (/usr/src/app/webpack:/node_modules/ipfs-utils/src/http.js:179:17)
    at Object.post [as add] (/usr/src/app/webpack:/node_modules/ipfs-http-client/src/add.js:13:27)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) 
debug Finished polling all sources stateChange: {
  "cacheChange": {},
  "sourcesToAdd": [],
  "sourcesToRemove": [],
  "assetsToAdd": [],
  "assetsToRemove": []
}
debug Applying state change stateChange: {
  "cacheChange": {},
  "sourcesToAdd": [],
  "sourcesToRemove": [],
  "assetsToAdd": [],
  "assetsToRemove": []
}
```

**Comment by dapplion** [comment]
Thanks for reporting! We will release a fixed version ASAP. The fixed is contained in this commit https://github.com/dappnode/DAppNodePackage-ipfs-pinner/commit/04d4a300170b141886829c40630c19e7231fb5ed
