### ISSUE TITLE
error Error: invalid response - 0

### ISSUE THREAD

**Issue by ligi** [dappnode/DAppNodePackage-ipfs-pinner#28]
I am seeing the following when trying to pin:

![Selection_534](https://user-images.githubusercontent.com/111600/82517669-e796d480-9b1d-11ea-8af7-ca916740e031.png)

From the logs:

```
info Starting cache DB cacheDbPath: "/usr/src/app/data/cachedb.json"
info IPFS HTTP API ipfsApiUrl: "http://ipfs.dappnode:5001"
info IPFS Cluster HTTP API clusterApiUrl: "http://ipfs-cluster.dappnode:9094"
info Web3 connected (ethers 4.0.39): http://fullnode.dappnode:8545 
(node:1) V8: /usr/src/app/index.js:787 Invalid asm.js: Unexpected token
info Webserver on 80, /usr/src/app/dist 
GET / 200 96.508 ms - -
GET /static/css/main.27f7cbed.chunk.css 200 12.641 ms - 734
GET /static/js/main.250c2346.chunk.js 200 11.676 ms - -
GET /static/js/2.91517ccb.chunk.js 200 11.845 ms - -
info Client connected 34TijuOnY0FnVSrIAAAA 
error Error: invalid response - 0
    at t.XMLHttpRequest.s.onreadystatechange (/usr/src/app/webpack:/node_modules/ethers/utils/web.js:84:29)
    at t.XMLHttpRequest.event [as dispatchEvent] (/usr/src/app/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:19)
    at dispatchEvent (/usr/src/app/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at t.XMLHttpRequest.setState [as handleError] (/usr/src/app/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:5)
    at ClientRequest.handleError (/usr/src/app/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketErrorListener (_http_client.js:415:9)
    at Socket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3) statusCode: 0 - responseText: "Error: getaddrinfo EAI_AGAIN fullnode.dappnode\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)"
(node:1) UnhandledPromiseRejectionWarning: Error: invalid response - 0
    at t.XMLHttpRequest.s.onreadystatechange (/usr/src/app/webpack:/node_modules/ethers/utils/web.js:84:29)
    at t.XMLHttpRequest.event [as dispatchEvent] (/usr/src/app/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:19)
    at dispatchEvent (/usr/src/app/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at t.XMLHttpRequest.setState [as handleError] (/usr/src/app/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:5)
    at ClientRequest.handleError (/usr/src/app/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketErrorListener (_http_client.js:415:9)
    at Socket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
GET /static/css/main.27f7cbed.chunk.css.map 200 3.339 ms - -
GET /static/js/main.250c2346.chunk.js.map 200 7.632 ms - -
GET /static/js/2.91517ccb.chunk.js.map 200 7.799 ms - -
```

Note: the node is not yet fully synced - but as far as I understand it should use the remote then?
![Selection_535](https://user-images.githubusercontent.com/111600/82517738-0a28ed80-9b1e-11ea-9651-6889064a27e7.png)

EDIT: now fully synced - but still seeing the issue.

![Selection_536](https://user-images.githubusercontent.com/111600/82522626-495d3b80-9b2a-11ea-9119-02c53a9aeb36.png)

**Comment by dapplion** [comment]
ethers is not great at error reporting. I've added a fix in the next release that should show the full error instead of "invalid response - 0" https://github.com/dappnode/DAppNodePackage-ipfs-pinner/pull/26. After releasing this version and updating to it, you should get more information about connection errors.
